INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Rafael','Lynch','now()','CI','16800117 4211');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Whitney','Cross','now()','CI','16220614 5852');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Illana','Roy','now()','NIT','16091122 3899');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Mallory','Juarez','now()','NIT','16040425 3247');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Ori','Burris','now()','CI','16300905 0885');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Camden','Cortez','now()','CI','16881223 5912');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Todd','Gill','now()','NIT','16291115 9602');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Holmes','Carrillo','now()','NIT','16220602 5203');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Kellie','Oneil','now()','CI','16760920 9031');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Yuli','Rhodes','now()','CI','16280819 8606');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Hakeem','Lamb','now()','NIT','16840216 3664');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Demetria','Hess','now()','NIT','16670523 9538');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Kasimir','Middleton','now()','CI','16320825 2142');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Aphrodite','Williamson','now()','CI','16960610 6855');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Taylor','Mullins','now()','NIT','16000122 5101');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Blythe','Salinas','now()','NIT','16330109 4508');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Eric','Hurst','now()','CI','16160104 7457');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('John','Beard','now()','CI','16610606 8122');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Quon','Vargas','now()','NIT','16470915 3334');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Camilla','Watts','now()','NIT','16210921 0043');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Cameran','Mercer','now()','CI','16900626 2167');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Risa','Mosley','now()','CI','16450412 6691');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Jasper','Bond','now()','NIT','16511106 6444');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Amity','Brewer','now()','NIT','16270322 8201');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Carter','Russell','now()','CI','16260302 8479');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Blair','Mcneil','now()','CI','16351224 4496');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Riley','Mcmillan','now()','NIT','16140824 4257');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Karly','Cannon','now()','NIT','16440406 4208');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Silas','Nichols','now()','CI','16260318 7135');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Yardley','Moreno','now()','CI','16560928 9946');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Irene','Norton','now()','NIT','16941003 9227');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Sydnee','Martin','now()','NIT','16761014 4037');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Regina','Dennis','now()','CI','16631126 9069');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Ramona','Wiggins','now()','CI','16521122 5148');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Keiko','Gilliam','now()','NIT','16130204 1262');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Madonna','Cabrera','now()','NIT','16240523 0455');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Hollee','Peters','now()','CI','16151112 8728');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Melvin','West','now()','CI','16330324 5785');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Leandra','Fernandez','now()','NIT','16901016 1587');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Molly','Mckenzie','now()','NIT','16111226 6380');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Daryl','Best','now()','CI','16060116 6549');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Brendan','Bradford','now()','CI','16901014 0557');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Halla','Carson','now()','NIT','16511228 8229');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Hayfa','Shelton','now()','NIT','16770209 0445');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Malachi','Marsh','now()','CI','16230724 6435');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Nola','Thompson','now()','CI','16700525 9135');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Conan','Fowler','now()','NIT','16560708 8696');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Acton','Dale','now()','NIT','16810919 9615');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Myles','Foreman','now()','CI','16441204 2584');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Jolie','Franco','now()','CI','16111126 4733');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Buffy','Terrell','now()','NIT','16320527 6367');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Iola','Lancaster','now()','NIT','16670402 9864');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Bevis','Moses','now()','CI','16060318 5885');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Wynne','Herrera','now()','CI','16351006 2692');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Keelie','Hester','now()','NIT','16810818 7066');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Raven','Bonner','now()','NIT','16131120 5288');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Isabelle','Best','now()','CI','16870928 9808');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Kessie','Cardenas','now()','CI','16511123 3770');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Reese','Parrish','now()','NIT','16920504 0141');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Forrest','Huffman','now()','NIT','16640523 0423');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Bell','Berg','now()','CI','16840402 1456');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Bruce','Wheeler','now()','CI','16480821 4078');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Maxwell','Morse','now()','NIT','16940316 7944');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Kennedy','Rosa','now()','NIT','16061214 5979');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Alec','Crane','now()','CI','16001110 4189');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Melvin','Austin','now()','CI','16591201 6358');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Macy','Gross','now()','NIT','16821215 9688');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Erin','Manning','now()','NIT','16310110 2634');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Jacob','Cash','now()','CI','16820718 5201');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Ezra','Gillespie','now()','CI','16041101 3345');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Callum','Peters','now()','NIT','16360922 3361');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Mohammad','Ewing','now()','NIT','16520402 7832');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Nita','Sargent','now()','CI','16330310 2895');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Anjolie','Dyer','now()','CI','16251213 9524');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Whitney','Jackson','now()','NIT','16930227 1946');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Oprah','Finley','now()','NIT','16531102 2742');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Andrew','Swanson','now()','CI','16300329 4083');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Molly','Suarez','now()','CI','16170118 7435');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Sebastian','Barton','now()','NIT','16840821 4602');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Plato','Carpenter','now()','NIT','16631118 7816');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Brielle','Lynn','now()','CI','16600312 9084');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Amir','Perry','now()','CI','16190421 8391');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Amber','Vargas','now()','NIT','16990628 3750');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Nissim','Carpenter','now()','NIT','16550711 0574');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Raven','Silva','now()','CI','16900924 1077');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Tanner','Walton','now()','CI','16950625 7501');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Rebekah','Ellison','now()','NIT','16350829 8571');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Kirk','Garrison','now()','NIT','16220416 2370');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Caldwell','Nieves','now()','CI','16180430 6353');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Neville','Frost','now()','CI','16910226 1089');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Mark','Santiago','now()','NIT','16810115 8205');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Harding','Singleton','now()','NIT','16190124 6833');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Vivian','Wooten','now()','CI','16011106 5215');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Buffy','Holland','now()','CI','16680115 2346');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Samantha','Galloway','now()','NIT','16120925 7201');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Jonah','Jarvis','now()','NIT','16211106 4354');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Mechelle','Warner','now()','CI','16651015 3924');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('James','Downs','now()','CI','16441211 9721');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Lydia','Merrill','now()','NIT','16820729 8095');
INSERT INTO "t_person" (first_name,last_name,created_date,document_type,document_id) VALUES ('Gay','Johns','now()','NIT','16900222 5978');

INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('PHN15AQV2GY','et netus',250,'ipsum primis in','[]','quis,','magna,','pharetra','SPARE_PARTS','vulputate, risus a ultricies adipiscing,','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('ZOM72LJN6UL','Cum sociis',264,'imperdiet, erat nonummy','[]','vitae','Ut','ornare','SPARE_PARTS','bibendum sed, est. Nunc laoreet','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('JVH32VDA4ZN','id sapien.',97,'sit amet, consectetuer','[]','dictum','fringilla','mauris','SPARE_PARTS','Aliquam erat volutpat. Nulla facilisis.','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('KVO81CMP0NF','quam dignissim',971,'augue porttitor interdum.','[]','Quisque','sociis','Vivamus','SPARE_PARTS','porttitor interdum. Sed auctor odio','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('IEP74LPJ5XO','et tristique',856,'vel, faucibus id,','[]','purus,','ut','nonummy.','TOOLS','vel, convallis in, cursus et,','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('GET20TQA3SK','facilisis facilisis,',694,'vitae purus gravida','[]','purus','penatibus','quam,','TOOLS','a tortor. Nunc commodo auctor','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('KUX59HST3UA','mollis. Phasellus',844,'mauris, rhoncus id,','[]','mattis','purus','Pellentesque','TOOLS','parturient montes, nascetur ridiculus mus.','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('EIR87IGZ9PU','facilisis. Suspendisse',455,'Donec luctus aliquet','[]','neque.','mattis.','ac','TOOLS','malesuada fringilla est. Mauris eu','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('EKE69THY3IN','dapibus quam',79,'mus. Aenean eget','[]','dapibus','fermentum','pede,','SUPPLIES','Donec non justo. Proin non','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('KVM74WPD7WV','Fusce feugiat.',329,'mauris. Suspendisse aliquet','[]','est,','arcu.','vitae','SUPPLIES','pulvinar arcu et pede. Nunc','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('QJZ44URW9GA','suscipit, est',125,'metus facilisis lorem','[]','Curabitur','facilisis,','interdum','SUPPLIES','lorem, sit amet ultricies sem','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('YTK35PNE8GP','Aenean euismod',391,'interdum. Curabitur dictum.','[]','nulla','commodo','eget','SUPPLIES','massa. Mauris vestibulum, neque sed','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('GML93QVC0HE','eleifend non,',774,'nibh lacinia orci,','[]','gravida','non','ligula.','EQUIPMENT','felis, adipiscing fringilla, porttitor vulputate,','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('VEU85PWY9GA','tempor bibendum.',580,'faucibus leo, in','[]','auctor','metus','tempor','EQUIPMENT','Aliquam vulputate ullamcorper magna. Sed','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('PCQ97MVL4MD','mattis semper,',56,'arcu. Curabitur ut','[]','faucibus.','Cras','eu','EQUIPMENT','at arcu. Vestibulum ante ipsum','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('MCY33NZA4TY','vulputate, posuere',803,'magna, malesuada vel,','[]','tempus','Proin','ut','EQUIPMENT','egestas blandit. Nam nulla magna,','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('LWX48SXW6WP','Curabitur ut',240,'in aliquet lobortis,','[]','non','mi,','et','SPARE_PARTS','augue porttitor interdum. Sed auctor','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('KAO54WBO9QJ','Cras dictum',714,'mauris ut mi.','[]','erat,','pede.','Sed','SPARE_PARTS','lorem, sit amet ultricies sem','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('ELL35LUU9LB','id, erat.',608,'et magnis dis','[]','Maecenas','imperdiet','Ut','SPARE_PARTS','in faucibus orci luctus et','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('QAR27EKG7SX','sit amet',120,'eu, accumsan sed,','[]','sed','ultrices','in','SPARE_PARTS','sit amet lorem semper auctor.','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('IIE16MIM4UT','natoque penatibus',507,'libero. Proin sed','[]','risus.','non','at','TOOLS','vitae, sodales at, velit. Pellentesque','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('SRO58GVH6HD','porttitor interdum.',502,'magna. Duis dignissim','[]','accumsan','dictum','arcu','TOOLS','a, arcu. Sed et libero.','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('CDA85ODN1IO','interdum. Curabitur',872,'nec mauris blandit','[]','auctor.','Maecenas','felis.','TOOLS','lobortis tellus justo sit amet','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('SIY95QOQ4ER','malesuada augue',492,'dolor. Fusce feugiat.','[]','Donec','dui.','nibh','TOOLS','augue ac ipsum. Phasellus vitae','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('RQG58LHT3FP','turpis egestas.',282,'interdum enim non','[]','non','ornare,','lorem','SUPPLIES','placerat. Cras dictum ultricies ligula.','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('HHZ60ZSN8ZT','ac orci.',357,'sodales elit erat','[]','est.','Mauris','massa.','SUPPLIES','Fusce mi lorem, vehicula et,','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('TAR24JCE0UW','scelerisque scelerisque',605,'odio. Aliquam vulputate','[]','Suspendisse','aliquet','nulla.','SUPPLIES','Vivamus nisi. Mauris nulla. Integer','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('FRT69RIY6CJ','sem egestas',952,'facilisis vitae, orci.','[]','nonummy','molestie','ac','SUPPLIES','Donec dignissim magna a tortor.','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('JZS05OQR4VW','est arcu',572,'molestie orci tincidunt','[]','Suspendisse','elit.','vel','EQUIPMENT','lacus. Etiam bibendum fermentum metus.','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('WEJ55MGO3HK','Duis a',373,'Vivamus nibh dolor,','[]','Cras','arcu.','a,','EQUIPMENT','Cum sociis natoque penatibus et','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('NVM09JYE6YM','eu neque',184,'quam quis diam.','[]','Mauris','pede','In','EQUIPMENT','iaculis, lacus pede sagittis augue,','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('NDN69YRS9FX','a tortor.',177,'Donec vitae erat','[]','nulla','velit.','dolor','EQUIPMENT','dignissim lacus. Aliquam rutrum lorem','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('RZT25JBY0OV','aliquet. Proin',143,'posuere cubilia Curae;','[]','arcu','pretium','nec,','SPARE_PARTS','amet, consectetuer adipiscing elit. Etiam','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('BEM87GKX1JV','ullamcorper. Duis',242,'metus facilisis lorem','[]','ultricies','amet,','turpis','SPARE_PARTS','eros. Proin ultrices. Duis volutpat','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('YLQ46GLL5SW','rutrum non,',921,'ante, iaculis nec,','[]','massa.','dui.','dui.','SPARE_PARTS','blandit congue. In scelerisque scelerisque','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('DHO09GHN1WS','nisl. Quisque',106,'pharetra ut, pharetra','[]','vitae,','et,','ultrices','SPARE_PARTS','Aliquam auctor, velit eget laoreet','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('LDZ05PHN0OC','euismod urna.',230,'feugiat. Sed nec','[]','blandit','metus.','Duis','TOOLS','lectus sit amet luctus vulputate,','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('LDQ70VON6VC','diam. Pellentesque',424,'amet diam eu','[]','lorem','nunc','interdum.','TOOLS','dis parturient montes, nascetur ridiculus','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('TMO26KNC7EF','scelerisque dui.',578,'Sed congue, elit','[]','mi','Quisque','non,','TOOLS','purus mauris a nunc. In','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('EIN79BSR7CJ','rhoncus. Proin',45,'Nulla facilisis. Suspendisse','[]','mauris','ligula.','diam.','TOOLS','dui augue eu tellus. Phasellus','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('QRZ78ISG3RR','accumsan neque',590,'sagittis. Nullam vitae','[]','a','nunc','arcu.','SUPPLIES','at lacus. Quisque purus sapien,','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('JJL86ITM1SA','Fusce mi',310,'magna. Phasellus dolor','[]','magna.','sagittis','lobortis,','SUPPLIES','elementum, dui quis accumsan convallis,','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('MIM48AZU4AC','pellentesque. Sed',950,'amet diam eu','[]','elit.','elementum','neque','SUPPLIES','aliquet nec, imperdiet nec, leo.','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('WJB78FXT9BC','est, vitae',16,'posuere, enim nisl','[]','non','feugiat','non,','SUPPLIES','elit erat vitae risus. Duis','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('XNC06VSJ2NR','suscipit nonummy.',566,'Curae; Phasellus ornare.','[]','Phasellus','lobortis','velit','EQUIPMENT','mattis semper, dui lectus rutrum','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('VJD07HDV9LH','Proin non',233,'risus. In mi','[]','mattis.','odio','sit','EQUIPMENT','cursus in, hendrerit consectetuer, cursus','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('VYR88QNW5QS','sem mollis',691,'accumsan sed, facilisis','[]','amet','Nunc','sapien,','EQUIPMENT','eget ipsum. Suspendisse sagittis. Nullam','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('ESA91PIL4DZ','cursus a,',415,'tincidunt pede ac','[]','et,','Proin','ipsum.','EQUIPMENT','ligula. Aenean gravida nunc sed','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('FZR71SJS9RX','Fusce fermentum',731,'turpis egestas. Aliquam','[]','orci.','arcu.','Integer','SPARE_PARTS','mauris sit amet lorem semper','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('YKR31MAX7ZP','lobortis quam',943,'commodo tincidunt nibh.','[]','iaculis','ridiculus','sagittis','SPARE_PARTS','iaculis enim, sit amet ornare','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('MXM10JVO3RZ','turpis non',772,'odio. Nam interdum','[]','egestas','egestas','in','SPARE_PARTS','gravida. Aliquam tincidunt, nunc ac','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('KWK75BIY6OO','risus. Donec',893,'ac facilisis facilisis,','[]','mollis','Quisque','Duis','SPARE_PARTS','Nullam enim. Sed nulla ante,','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('QUX26ZTG6JM','quam vel',509,'neque. Nullam ut','[]','ipsum','nibh.','mauris.','TOOLS','egestas nunc sed libero. Proin','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('LVF69VQU8AB','ultricies ligula.',337,'a feugiat tellus','[]','feugiat','Proin','elementum','TOOLS','arcu. Vestibulum ante ipsum primis','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('GKU61HBU9NE','eros. Proin',611,'neque sed sem','[]','Aenean','mus.','egestas','TOOLS','mollis vitae, posuere at, velit.','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('PZF20WJF3UW','eu metus.',671,'quis, pede. Suspendisse','[]','ipsum','dolor,','eget','TOOLS','nascetur ridiculus mus. Donec dignissim','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('GIH43XJA3DN','lacinia mattis.',231,'nisi nibh lacinia','[]','in','nec','enim','SUPPLIES','Nam nulla magna, malesuada vel,','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('LQE67IAM1NQ','velit dui,',247,'eu, ultrices sit','[]','ipsum','odio,','sapien','SUPPLIES','dis parturient montes, nascetur ridiculus','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('ZJP37QGK1JK','sit amet',208,'lobortis ultrices. Vivamus','[]','Duis','ut','ligula','SUPPLIES','felis ullamcorper viverra. Maecenas iaculis','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('CAA38TUG1DY','lectus ante',829,'sed turpis nec','[]','metus','feugiat','non,','SUPPLIES','aliquam, enim nec tempus scelerisque,','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('GLD66QQL1GN','nec tellus.',901,'ligula consectetuer rhoncus.','[]','dapibus','Cras','eget','EQUIPMENT','aliquam, enim nec tempus scelerisque,','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('ETG90AKF7FR','Cras eget',667,'ac arcu. Nunc','[]','ornare','Nunc','Morbi','EQUIPMENT','semper et, lacinia vitae, sodales','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('XIR62IUP1AF','at, egestas',556,'ac tellus. Suspendisse','[]','dolor.','eget','Etiam','EQUIPMENT','ac libero nec ligula consectetuer','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('ETL90XDD7NA','gravida sit',192,'Nulla tincidunt, neque','[]','enim,','non,','dis','EQUIPMENT','sem semper erat, in consectetuer','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('XMS65KOQ7YD','varius ultrices,',396,'porttitor interdum. Sed','[]','ridiculus','non','dictum.','SPARE_PARTS','Nulla semper tellus id nunc','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('RFN85BON2UU','semper. Nam',486,'Morbi quis urna.','[]','euismod','ante','Duis','SPARE_PARTS','Sed malesuada augue ut lacus.','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('OHD12UDS0IC','tempus risus.',381,'Cras convallis convallis','[]','ac,','est','rutrum','SPARE_PARTS','dolor dolor, tempus non, lacinia','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('MAA03GPN4ZX','varius. Nam',914,'nec tempus mauris','[]','eget','posuere','sed','SPARE_PARTS','porttitor interdum. Sed auctor odio','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('NFF53IND9FC','commodo hendrerit.',141,'orci quis lectus.','[]','fermentum','Lorem','molestie','TOOLS','in magna. Phasellus dolor elit,','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('QTB02EOY2HJ','Aenean egestas',182,'turpis nec mauris','[]','neque','litora','scelerisque,','TOOLS','Nunc ullamcorper, velit in aliquet','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('ZFV66RDX0EX','eget laoreet',666,'Suspendisse eleifend. Cras','[]','sodales','pede,','dui.','TOOLS','ipsum dolor sit amet, consectetuer','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('WDS78GKM1VI','cursus. Nunc',547,'dui lectus rutrum','[]','justo','pede','non,','TOOLS','Vivamus molestie dapibus ligula. Aliquam','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('TXQ52YDR5SO','arcu iaculis',92,'augue porttitor interdum.','[]','tempus,','et','cursus','SUPPLIES','et arcu imperdiet ullamcorper. Duis','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('MXH17NDW0KF','neque. Nullam',170,'ipsum dolor sit','[]','congue.','Integer','urna,','SUPPLIES','risus. Donec egestas. Duis ac','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('HAS16UQU9XJ','ut quam',100,'in lobortis tellus','[]','Nulla','a,','a,','SUPPLIES','eu nibh vulputate mauris sagittis','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('WBP42CBC2HQ','eu, accumsan',335,'neque et nunc.','[]','est.','a','pede.','SUPPLIES','mollis nec, cursus a, enim.','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('QLG35EGI5WU','erat, in',134,'In at pede.','[]','lorem,','Morbi','Pellentesque','EQUIPMENT','elit fermentum risus, at fringilla','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('DJD32UXH3SA','Nulla tincidunt,',360,'Pellentesque ut ipsum','[]','Mauris','a','nascetur','EQUIPMENT','non, sollicitudin a, malesuada id,','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('DRU84NVP6JB','tristique pharetra.',399,'elit erat vitae','[]','Nulla','ullamcorper','ultricies','EQUIPMENT','Nam porttitor scelerisque neque. Nullam','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('QLU87SCX4NO','nascetur ridiculus',529,'Nunc mauris. Morbi','[]','placerat.','ut','odio.','EQUIPMENT','quam, elementum at, egestas a,','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('TQK77WUV7GR','Curabitur vel',159,'non, lobortis quis,','[]','euismod','nec','eleifend,','SPARE_PARTS','risus, at fringilla purus mauris','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('SMU34WVX9WP','mi felis,',90,'eu, eleifend nec,','[]','Suspendisse','ullamcorper,','cursus','SPARE_PARTS','tellus. Aenean egestas hendrerit neque.','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('QAQ33CYA4OC','nisl. Quisque',986,'tempor erat neque','[]','luctus','et','placerat,','SPARE_PARTS','varius orci, in consequat enim','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('ANW66JZI0SZ','erat volutpat.',911,'massa. Suspendisse eleifend.','[]','Sed','Etiam','Donec','SPARE_PARTS','arcu. Vestibulum ut eros non','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('WTS14APP0ZB','nulla at',813,'tristique pellentesque, tellus','[]','luctus','vulputate','enim,','TOOLS','urna, nec luctus felis purus','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('TIT39CLL0AE','nec mauris',293,'id, ante. Nunc','[]','lorem,','orci','sit','TOOLS','tortor nibh sit amet orci.','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('ZKW28MHU1VQ','mauris elit,',348,'ut odio vel','[]','montes,','vel','vel,','TOOLS','euismod ac, fermentum vel, mauris.','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('FIS66TFG5FW','ante. Nunc',495,'congue. In scelerisque','[]','elit,','Integer','amet','TOOLS','luctus sit amet, faucibus ut,','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('STU42PIV2XG','nisi. Mauris',916,'sit amet lorem','[]','parturient','malesuada','non','SUPPLIES','velit. Quisque varius. Nam porttitor','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('FUX07WUV4MY','id, ante.',892,'nascetur ridiculus mus.','[]','tincidunt,','eu,','at','SUPPLIES','Morbi non sapien molestie orci','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('VVX40KJV2US','quis diam.',98,'eget, venenatis a,','[]','mauris','fringilla','Praesent','SUPPLIES','fringilla, porttitor vulputate, posuere vulputate,','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('MOS81GVQ4GZ','pellentesque, tellus',683,'non sapien molestie','[]','tincidunt','sit','tincidunt','SUPPLIES','Vivamus nisi. Mauris nulla. Integer','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('RUE71VCE1QN','pulvinar arcu',494,'egestas a, dui.','[]','magna','Nam','varius','EQUIPMENT','Integer sem elit, pharetra ut,','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('XRJ95SGW1MA','dignissim pharetra.',547,'non enim. Mauris','[]','purus,','tincidunt','volutpat.','EQUIPMENT','est arcu ac orci. Ut','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('ANR90ZCY6HD','vehicula risus.',808,'lectus pede, ultrices','[]','sit','magna.','lorem','EQUIPMENT','fames ac turpis egestas. Fusce','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('GXF16CBC3LL','luctus. Curabitur',139,'hendrerit neque. In','[]','Praesent','lectus','libero','EQUIPMENT','tristique neque venenatis lacus. Etiam','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('APB72IOD3QD','Duis cursus,',459,'consequat nec, mollis','[]','dictum','consequat','velit.','SPARE_PARTS','lorem fringilla ornare placerat, orci','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('ANN50IXL4IA','per conubia',167,'nascetur ridiculus mus.','[]','Pellentesque','taciti','magna.','SPARE_PARTS','gravida. Praesent eu nulla at','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('MOF99BQC9ZE','Fusce feugiat.',519,'interdum libero dui','[]','id','nec,','Pellentesque','SPARE_PARTS','lacinia mattis. Integer eu lacus.','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('OGO23DYD6OD','ullamcorper. Duis',656,'mollis non, cursus','[]','et,','Nullam','luctus','SPARE_PARTS','eros turpis non enim. Mauris','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('LQW09KUN9VZ','dui. Fusce',975,'Curabitur egestas nunc','[]','amet,','ligula.','neque','SPARE_PARTS','eu dolor egestas rhoncus. Proin','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('LYT08PSD3GT','Vestibulum accumsan',533,'cubilia Curae; Donec','[]','adipiscing','Curae;','bibendum','SPARE_PARTS','Curabitur massa. Vestibulum accumsan neque','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('XHQ60NYV3ZQ','primis in',33,'dui. Fusce aliquam,','[]','Mauris','Integer','eget','SPARE_PARTS','tortor nibh sit amet orci.','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('VRM31MJW1IV','dictum mi,',938,'nec tempus mauris','[]','montes,','id','gravida','SPARE_PARTS','purus gravida sagittis. Duis gravida.','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('IVI00FKM1JD','eu nibh',767,'cursus et, magna.','[]','at','eu','neque','TOOLS','sed dui. Fusce aliquam, enim','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('MPQ24YGW4ZX','Fusce dolor',769,'morbi tristique senectus','[]','elit.','viverra.','sed','TOOLS','Duis volutpat nunc sit amet','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('TUN89NMY8YZ','ullamcorper viverra.',662,'dolor. Quisque tincidunt','[]','Suspendisse','Curabitur','dictum','TOOLS','ac, feugiat non, lobortis quis,','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('LMB85TDH9AC','mauris blandit',171,'molestie pharetra nibh.','[]','tincidunt','diam.','mi.','TOOLS','nisl sem, consequat nec, mollis','INACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('TEL47JJB6CQ','cursus non,',467,'natoque penatibus et','[]','commodo','lobortis','scelerisque','SUPPLIES','nulla at sem molestie sodales.','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('IKL90NKC8VJ','Nam consequat',253,'risus a ultricies','[]','non,','pretium','parturient','SUPPLIES','vestibulum lorem, sit amet ultricies','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('LKG13FKP4SO','dictum sapien.',970,'ante dictum mi,','[]','urna','Ut','nisi','SUPPLIES','Sed congue, elit sed consequat','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('ODP35CAK3KL','eget metus.',908,'sociis natoque penatibus','[]','vel','urna','vel','SUPPLIES','ultrices. Duis volutpat nunc sit','EXPIRED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('TZM29TZG3VS','Aliquam nec',16,'non sapien molestie','[]','Sed','sit','ac','EQUIPMENT','sollicitudin orci sem eget massa.','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('NCJ86EMB5OF','amet orci.',1,'lorem. Donec elementum,','[]','elit,','et,','convallis','EQUIPMENT','eget, dictum placerat, augue. Sed','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('NDG55VIU4SW','velit. Pellentesque',105,'tortor. Integer aliquam','[]','arcu','vel,','interdum','EQUIPMENT','Aliquam ultrices iaculis odio. Nam','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('TBN21SLA9QR','arcu eu',796,'dapibus id, blandit','[]','enim.','dictum','mauris','EQUIPMENT','Sed malesuada augue ut lacus.','DELETED',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('OKM73VVB6EM','quam a',272,'Aenean egestas hendrerit','[]','lobortis','arcu.','vel','SPARE_PARTS','vel pede blandit congue. In','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('WYQ14EFX6RB','quam a',319,'at, iaculis quis,','[]','ac','Nam','Proin','SPARE_PARTS','mi pede, nonummy ut, molestie','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('CWC20TZN7VZ','nascetur ridiculus',811,'nec, diam. Duis','[]','sapien','mattis','arcu','SPARE_PARTS','fermentum vel, mauris. Integer sem','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('TPW21BSY1YP','posuere at,',659,'scelerisque neque. Nullam','[]','magna','augue','venenatis','SPARE_PARTS','arcu. Curabitur ut odio vel','ACTIVE',now());
INSERT INTO "t_item" (code,name,default_price,description,images,part_number,manufacturer,model,item_type,notes,status,created_date) VALUES ('UIL76ROT9GL','tempor erat',628,'euismod urna. Nullam','[]','mi','eu','eu','TOOLS','quam. Pellentesque habitant morbi tristique','INACTIVE',now());

INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('adipiscing elit.','sit amet orci.','ACTIVE','now()','false');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('pede sagittis','elit, pretium et,','ACTIVE','now()','false');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('Integer aliquam','in, tempus eu,','ACTIVE','now()','true');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('risus, at','Nullam lobortis quam','ACTIVE','now()','false');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('pretium neque.','in, cursus et,','INACTIVE','now()','true');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('mattis. Integer','auctor velit. Aliquam','INACTIVE','now()','true');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('vel sapien','nonummy ipsum non','INACTIVE','now()','false');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('Morbi metus.','a felis ullamcorper','INACTIVE','now()','false');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('tincidunt vehicula','nec, leo. Morbi','EXPIRED','now()','true');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('fermentum fermentum','mauris id sapien.','EXPIRED','now()','false');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('montes, nascetur','et nunc. Quisque','EXPIRED','now()','true');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('leo. Morbi','vulputate, nisi sem','EXPIRED','now()','true');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('non, luctus','orci. Ut semper','DELETED','now()','false');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('In tincidunt','Suspendisse aliquet molestie','DELETED','now()','false');
INSERT INTO "t_inventory" (name,description,status,created_date,allow_negative_stocks) VALUES ('tincidunt aliquam','Phasellus vitae mauris','DELETED','now()','false');


INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('imperdiet dictum','malesuada augue ut','ACTIVE','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('hendrerit a,','Nunc ut erat.','ACTIVE','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('Quisque ac','convallis in, cursus','ACTIVE','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('et arcu','metus. In lorem.','ACTIVE','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('Cras pellentesque.','eget metus eu','INACTIVE','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('parturient montes,','odio tristique pharetra.','INACTIVE','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('varius. Nam','ipsum dolor sit','INACTIVE','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('non, lobortis','adipiscing fringilla, porttitor','INACTIVE','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('ac orci.','imperdiet ornare. In','EXPIRED','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('sed, sapien.','vel arcu. Curabitur','EXPIRED','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('lectus pede','egestas. Sed pharetra,','EXPIRED','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('sapien molestie','diam nunc, ullamcorper','EXPIRED','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('consequat enim','aliquam arcu. Aliquam','DELETED','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('odio semper','placerat velit. Quisque','DELETED','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('adipiscing elit.','Nunc pulvinar arcu','DELETED','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('lacus. Etiam','libero. Donec consectetuer','DELETED','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('quam. Curabitur','blandit viverra. Donec','ACTIVE','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('semper cursus.','mauris elit, dictum','ACTIVE','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('a tortor.','et, rutrum eu,','ACTIVE','now()');
INSERT INTO "t_maintenance" (name,description,status,created_date) VALUES ('ipsum. Donec','laoreet lectus quis','ACTIVE','now()');

INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('mauris', 'ITEM_CATEGORY', 'id, libero. Donec','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('Sed', 'ITEM_CATEGORY', 'Aenean sed pede','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('auctor', 'ITEM_CATEGORY', 'urna. Nunc quis','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('sed', 'ITEM_CATEGORY', 'luctus sit amet,','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('Ut', 'ITEM_CATEGORY', 'ut, pharetra sed,','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('consequat', 'ITEM_CATEGORY', 'Donec est. Nunc','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('enim', 'EMPLOYEE_JOB_CATEGORY', 'fringilla est. Mauris','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('et', 'EMPLOYEE_JOB_CATEGORY', 'Aenean egestas hendrerit','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('dui', 'EMPLOYEE_JOB_CATEGORY', 'semper auctor. Mauris','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('libero', 'EMPLOYEE_JOB_CATEGORY', 'penatibus et magnis','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('tellus', 'EMPLOYEE_JOB_CATEGORY', 'eget, venenatis a,','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('Phasellus', 'ITEM_CATEGORY', 'elementum at, egestas','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('ultricies', 'ITEM_CATEGORY', 'nunc ac mattis','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('Mauris', 'ITEM_CATEGORY', 'est, mollis non,','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('sollicitudin', 'ITEM_CATEGORY', 'blandit mattis. Cras','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('fringilla', 'ITEM_CATEGORY', 'nonummy ipsum non','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('et', 'ITEM_CATEGORY', 'fermentum convallis ligula.','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('vulputate', 'ITEM_CATEGORY', 'Proin dolor. Nulla','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('magna', 'ITEM_CATEGORY', 'eget laoreet posuere,','now()');
INSERT INTO "t_category" (name,scope, description,created_date) VALUES ('mus.', 'ITEM_CATEGORY', 'aptent taciti sociosqu','now()');

INSERT INTO "t_unit" (key,label,created_date) VALUES ('SECOND','Second','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('MINUTE','Minute','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('HOUR','Hour','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('DAY','Day','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('WEEK','Week','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('MONTH','Month','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('YEAR','Year','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('Sed','sit amet,','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('montes,','amet, faucibus','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('enim.','nulla ante,','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('dictum','lobortis quis,','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('eget,','convallis in,','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('eget','sit amet,','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('adipiscing,','amet massa.','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('cubilia','Quisque libero','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('sapien','euismod et,','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('orci.','orci luctus','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('non,','vel, convallis','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('lacus.','tellus justo','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('dictum','sem. Pellentesque','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('ullamcorper','odio. Aliquam','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('congue','nec quam.','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('nibh','Mauris blandit','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('eget','diam. Duis','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('diam.','interdum libero','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('mauris','sollicitudin adipiscing','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('et','nisi nibh','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('tellus','Proin velit.','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('turpis.','dis parturient','now()');
INSERT INTO "t_unit" (key,label,created_date) VALUES ('Donec','posuere, enim','now()');

INSERT INTO "t_equipment"
select  item_id,
        random() * 9 + 1 as priority,
        random() * 23 + 1 as hours_average_daily_use,
        true as out_of_service,
        now() as purchase_date,
        null as parent_id,
        null,
        now() as created_date
from t_item where item_type = 'EQUIPMENT';

insert into t_employee
select
       person_id as employee_id,
       now() as hire_date,
       random() * 2000 + 1 as salary,
       (SELECT category_id FROM t_category where scope = 'EMPLOYEE_JOB_CATEGORY' ORDER BY RANDOM() LIMIT 1) as employee_job_id,
        now() as created_date
from t_person limit 50;
